- index.js
- index.test.js
We should be using caseless header checks; however, there is very
little value in the header check anyway because since we are
contacting the Google metadata service. Requiring a header in the
response makes it harder to nock the metadata service.
Fixes: https://github.com/stephenplusplus/gcp-metadata/issues/6
> less strict response check

- index.ts
The error object being returned has a `code` field as well. This PR adds that
> fix: add code field for callback error type

- index.test.ts
- index.ts
`Error|NodeJS.ErrnoException` turns out not to be the equivalent of `NodeJS.ErrnoException`: a function with the signature defined by `Callback` will always see `error` as an `Error` object, as it is a supertype of `ErrnoException`.
@ofrobots PTAL.
> fix: remove Error from type of callback error object

- src/index.ts
This updates the url to use v1beta1, which makes things work on the GCF.
> fix: use v1beta1 instead of v1 to support GCF

- package.json
- src/index.ts
- test/index.test.ts
`assert.throws` doesn't seem to handle async/await.  To work around that in the current tests, I was trying to do a catch and assert.  That was causing issues (as found [here](https://github.com/stephenplusplus/gcp-metadata/pull/24#discussion_r166140281).  To properly test throws, I moved us over to ava.  This uncovered a whole bunch of issues that are addressed here as well.  
The `.serial` stuff is required because of our use of `nock`.
> test: switch to ava

- src/index.ts
After a fair bit of manual testing, we figured out that the v1/ path on GCF works ONLY if you're passing the right request headers. The tests are now fixed up to verify this.  We also found that GCF doesn't respond to the trailing dot for DNS lookups, so we need to roll that perf change back.
> fix: use the v1 path and remove trailing dot

- README.md
- package.json
- src/index.ts
- test/index.test.ts
This could be contentious :)   I was having a ton of trouble getting this to work with both callbacks and promises.  I took at a look at the dependents...  and they're all libs we own:
https://www.npmjs.com/browse/depended/gcp-metadata
How about we just ruthlessly break this API and only support promise based programming?
> feat: switch to promises

- .circleci/config.yml
- .gitignore
- README.md
- package.json
@stephenplusplus we would need you to go here to set this up :)
https://codecov.io/gh/stephenplusplus/gcp-metadata
> chore: add code coverage

- src/index.ts
- test/index.test.ts
Adding this in response to the feedback here:
https://github.com/google/google-auth-library-nodejs/pull/284#discussion_r168261775
> feat: export headers to reduce duplication

- src/index.ts
- test/index.test.ts
There was a funny little bug hiding in here, where retries were only happening once.  The fix is to pass the instance object along with the config.  I also fixed up the tests to make sure we catch this in the future.
> fix: retry 3 times instead of once

- package.json
- test/fixtures/kitchen/package.json
- test/fixtures/kitchen/src/index.ts
- test/fixtures/kitchen/tsconfig.json
- test/kitchen.test.ts
I noticed that the greenkeeper PR to https://github.com/google/google-auth-library-nodejs/pull/288 was failing, and it looked like an issue with the generated d.ts.  It turned out the answer in this case was to upgrade that lib to TypeScript 2.7, but it made me realize we should probably have a d.ts test in this lib like the others.
> chore: TypeScript 2.7 and TypeScript test

- src/index.ts
- test/index.test.ts
Updating this to match the current behavior in google-auth-library.  We want to fail fast on network errors when checking if it's on GCE using `isAvailable`, but retry 3 times if it's a call to instance() or project().  This way checks that happen on non-GCE machines fail fast, but real queries are offered a little protection.
> feat: retry 3 times on network errors

- src/index.ts
- test/index.test.ts
We use the status code today in google-auth-library :)
> fix: propagate original exception on non-200 response codes

- src/index.ts
- test/index.test.ts
Failure to resolve the metadata service means that it is not available,
but right now we are swallowing all errors which makes it harder to
diagnose issues with detecting the environment.
This change is needed to debug the root cause of the failure to get auth credentials in https://github.com/googleapis/nodejs-logging-winston/issues/1#issuecomment-400640124.
> fix: do not swallow unexpected errors

- package.json
- test/index.test.ts
- test/kitchen.test.ts
- test/mocha.opts
I switched this over to ava at some point.  That was a mistake.  I am trying to standardize our stuff on on mocha, and I wanted to get code coverage working better, so we're back here.  It's actually faster than ava in this case 😆
> refactor: use mocha instead of ava

- README.md
- package.json
- src/index.ts
- test/fixtures/kitchen/src/index.ts
- test/index.test.ts
BREAKING CHANGE:  The `instance()` and `project()` methods are much more selective about which properties they will accept.  The only accepted properties are `params` and `properties`.
The `instance()` and `project()` methods also now directly return the data instead of a response object. 
---
I am trying to quarantine the types for Axios.  This makes it so we don't expose the underlying http client library. I am also making the set of acceptable properties you can pass into the options config an allow-list instead of an open obj, and checking it at runtime.  This is potentially very breaking, so I want thoughts here from @stephenplusplus and @ofrobots :)
> fix: quarantine axios config

- README.md
- package.json
- src/index.ts
- test/index.test.ts
By default axios would parse strings as JSON [1]. The strings returned
by the metadata service are not JSON. This causes strings with numbers
to be parsed as JavaScript Numbers which loses precision. Strings should
be left unperturbed.
1: https://github.com/axios/axios/blob/9005a54a8b42be41ca49a31dcfda915d1a91c388/lib/defaults.js#L60
> fix: properly handle large numbers in responses

- README.md
- src/index.ts
- test/index.test.ts
To prevent the Trace Agent from tracing metadata requests, we need to be able to set custom headers. This PR adds that ability.
> feat: allow custom headers

- CHANGELOG.md
- package.json
- samples/package.json
This pull request was generated using releasetool.
> chore: release gcp-metadata v0.9.0

- src/index.ts
I'm not entirely sure why this works today, but I noticed this while making some compatibility fixes in gaxios.  I think the intent here was to have `json-bigint` always do the `JSON.parse` of the response from the metadata server.  If that's the case - we should just ask for text from gaxios, since JSON is the default.
> fix: ask gaxios for text and not json

- test/index.test.ts
Looks like a type update that borked master.
> test: pass correct type to nock reply

- src/index.ts
This is coming up in:
- https://github.com/googleapis/nodejs-datastore/issues/481
- https://github.com/googleapis/cloud-trace-nodejs/issues/1114
DNS was probably a mistake
> fix: use IP for metadata server

- src/index.ts
see: https://github.com/googleapis/nodejs-logging-bunyan/issues/353
> fix: IP address takes 15 seconds to timeout, vs., metadata returning immediately

- src/index.ts
I've tested with `GOOGLE_APPLICATION_CREDENTIALS` set, and `gcloud` logged in, we only hit the metadata server IP if these authentication strategies are not found, in which case we will now timeout after `3s` rather than `15s`.
> fix: use 3s timeout rather than 15 default

- package.json
- src/index.ts
- test/index.test.ts
When running on non GCP environment, `isAvailable()` had two significant issues:
1. we were not properly catching timeout exceptions, causing exceptions to bubble all the way to the user.
2. a 3s timeout makes the cold-start time, even when an exception isn't bubbling, painful.
This PR addresses `1.` by properly detecting timeout issues, and treating this the same as `ENOENT` or `ENOTFOUND`.
It addresses `2.` by attempting both `http://metadata.google.internal.` and `http://169.254.169.254`, why?
* when running in a non-GCP environment `http://metadata.google.internal.` fails fast.
* when running in a GCP environment, there are some cases where `http://169.254.169.254` is significantly faster than DNS.
> feat!: isAvailable now tries both DNS and IP, choosing whichever responds first

- src/index.ts
- test/index.test.ts
Some users are getting the error code `ENETUNREACH`, rather than `ENOTFOUND`, or `ENOENT`, let's also catch this error code and treat it as an unavailable metadata server.
see: https://github.com/googleapis/nodejs-logging/issues/587
> feat: don't throw on ENETUNREACH

- src/index.ts
- test/index.test.ts
Allow the `DEBUG_AUTH` environment variable to be set, for debugging authentication issues (currently this is being added specifically to dig in to metadata request failures).
> feat: add DEBUG_AUTH for digging into authentication issues

- package.json
fix: update gaxios to 2.1.0 to resolve https-proxy-agent vulnerability https://www.npmjs.com/advisories/1184
> fix(deps): update gaxios

- src/index.ts
- test/index.test.ts
This introduces a configuration variable that allows the method used to detect GCP environments, `DETECT_GCP_RETRIES`, to be configured.
This is based on the hypothesis that both `IP` and `DNS` environment detection are sometimes failing. 
CC: @feywind, I would love to see if this addresses the issues you were seeing during the bootstrapping of `@google-cloud/pubsub`.
> feat: add environment variable for configuring environment detection

- src/index.ts
- test/index.test.ts
@soldair was noticing situations where a failure after a success in the authentication race, might lead to an unhandled rejection.
> fix: fastFailMetadataRequest should not reject, if response already happened

- src/index.ts
- test/index.test.ts
It was suggested that this might help reduce the overall request load against the metadata server in cloud functions, reducing connectivity issues.
see: https://github.com/googleapis/google-auth-library-nodejs/issues/798
> feat: cache response from isAvailable() method

- src/index.ts
- test/index.test.ts
Add `ECONNREFUSED` to our list of known errors.
see: #302,  https://github.com/googleapis/nodejs-logging-winston/issues/389
> feat: add ECONNREFUSED to list of known errors for isAvailable()

- system-test/system.ts
see: https://cloud.google.com/functions/docs/release-notes
> test: functions no longer default to allowing external connections

- src/index.ts
- test/index.test.ts
Trying to enumerate all of the network error codes that might crop up trying to connect to the metadata server has been a nuisance. As suggested in #331, let's instead warn when we observe an unexpected error code, and return `false` (representing a non-GCP environment).
Fixes #331
> feat: warn rather than throwing when we fail to connect to metadata server

- src/index.ts
- system-test/system.ts
- test/index.test.ts
Adds test for happy path of `gcp.isAvailable()` when `GCE_METADATA_IP` is set (I believe this was actually broken).
Also moved more logic to the `getBaseUrl()` helper added by @bojeil-google, moving away from overwrought logic for building URL in global scope, fixes #348.
> fix: do not check secondary host if GCE_METADATA_IP set
